# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b_returnhome = QtWidgets.QPushButton(self.centralwidget)
        self.b_returnhome.setGeometry(QtCore.QRect(160, 370, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.b_returnhome.setFont(font)
        self.b_returnhome.setObjectName("b_returnhome")
        self.l_about = QtWidgets.QLabel(self.centralwidget)
        self.l_about.setGeometry(QtCore.QRect(40, 170, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.l_about.setFont(font)
        self.l_about.setTextFormat(QtCore.Qt.PlainText)
        self.l_about.setAlignment(QtCore.Qt.AlignCenter)
        self.l_about.setObjectName("l_about")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_returnhome.setText(_translate("MainWindow", "BACK"))
        self.l_about.setText(_translate("MainWindow", "Developed by: Salik, Gatab, Hombre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
