# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b_custom = QtWidgets.QPushButton(self.centralwidget)
        self.b_custom.setGeometry(QtCore.QRect(10, 330, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.b_custom.setFont(font)
        self.b_custom.setFlat(False)
        self.b_custom.setObjectName("b_custom")
        self.b_login = QtWidgets.QPushButton(self.centralwidget)
        self.b_login.setGeometry(QtCore.QRect(190, 330, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.b_login.setFont(font)
        self.b_login.setObjectName("b_login")
        self.b_about = QtWidgets.QPushButton(self.centralwidget)
        self.b_about.setGeometry(QtCore.QRect(340, 330, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.b_about.setFont(font)
        self.b_about.setObjectName("b_about")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_custom.setText(_translate("MainWindow", "Custom Account"))
        self.b_login.setText(_translate("MainWindow", "Login Miles"))
        self.b_about.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
